spring.application.name=NotificationService


# Server configuration
server.port=8083

# RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# (Optional) Additional email configuration can be added if you use JavaMailSender,
# for example:
 spring.mail.host=smtp.example.com
 spring.mail.port=587
 spring.mail.username=prarthana130503@gmail.com
 spring.mail.password=Poo@1305
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true
